# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [24]:
chipo = pd.read_excel("/kaggle/input/chipotle/chipotle_sample_data.xlsx")

### Step 3. Assign it to a variable called chipo.

In [25]:
chipo.head()

   order_id            item_name  quantity  item_price
0         1         Chicken Bowl         2        8.49
1         2        Steak Burrito         1        9.25
2         3         Chicken Bowl         1        8.49
3         4  Chips and Guacamole         2        4.45
4         5         Chicken Bowl         1        8.49

### Step 4. See the first 10 entries

In [26]:
chipo.head(10)

   order_id            item_name  quantity  item_price
0         1         Chicken Bowl         2        8.49
1         2        Steak Burrito         1        9.25
2         3         Chicken Bowl         1        8.49
3         4  Chips and Guacamole         2        4.45
4         5         Chicken Bowl         1        8.49
5         6        Steak Burrito         2        9.25
6         7         Veggie Salad         1        7.00
7         8         Chicken Bowl         1        8.49
8         9  Chips and Guacamole         3        4.45
9        10        Steak Burrito         1        9.25

### Step 5. What is the number of observations in the dataset?

In [27]:
# Solution 1
chipo.shape

(10, 4)

In [28]:
# Solution 2
len(chipo)

10

### Step 6. What is the number of columns in the dataset?

In [29]:
len(chipo.columns)

4

### Step 7. Print the name of all the columns.

In [30]:
chipo.columns

Index(['order_id', 'item_name', 'quantity', 'item_price'], dtype='object')

### Step 8. How is the dataset indexed?

In [31]:
chipo.index

RangeIndex(start=0, stop=10, step=1)

### Step 9. Which was the most-ordered item?

In [32]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)

item_name
Chicken Bowl    5
Name: quantity, dtype: int64

### Step 10. For the most-ordered item, how many items were ordered?

In [34]:
ordered = chipo.groupby('item_name')['quantity'].sum().idxmax()
print(ordered)

Chicken Bowl

### Step 11. What was the most ordered item in the choice_description column?

In [35]:
chipo['item_price'].value_counts().head(1)

item_price
8.49    4
Name: count, dtype: int64

### Step 12. How many items were orderd in total?

In [36]:
chipo['quantity'].sum()

15

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [38]:
chipo['item_price'].dtype

dtype('float64')

#### Step 13.b. Create a lambda function and change the type of item price

In [41]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(str(x).replace('$', '')))

#### Step 13.c. Check the item price type

In [42]:
chipo['item_price'].dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [44]:
revenue = (chipo['quantity'] * chipo['item_price']).sum()
print(revenue)

108.70000000000002

### Step 15. How many orders were made in the period?

In [45]:
orders = chipo['order_id'].nunique()
print(orders)

10

### Step 16. What is the average revenue amount per order?

In [46]:
# Solution 1

chipo['total_price'] = chipo['quantity'] * chipo['item_price']
order_revenue = chipo.groupby('order_id')['total_price'].sum()
average_revenue = order_revenue.mean()
print(average_revenue)

10.870000000000001

In [47]:
# Solution 2
#meannnn
average_revenue = (chipo['quantity'] * chipo['item_price']).groupby(chipo['order_id']).sum().mean()
print(average_revenue)

10.870000000000001

### Step 17. How many different items are sold?

In [48]:
count_items = chipo['item_name'].nunique()
print(count_items)

4